version: '3'
services: 
  redis:
    container_name: redis       
    ports:
      - '6379:6379'  
    image: redis:6.2.6-alpine    
  web:
      build: .
      command: python mysite/manage.py runserver 0.0.0.0:8000      
      ports:
        - '8000:8000'
      depends_on:
        - redis             
           






